apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperAccount
metadata:
  name: mobile-developeraccount
spec:
  orgName: GlobexMobile
  providerAccountRef:
    name: 3scale-tenant-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: mobileuser.secret
type: Opaque
stringData:
  password: openshift
---


apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperUser
metadata:
  name: jane.mobile
spec:
  username: jane.mobile
  email: jane@mobile.com
  passwordCredentialsRef:
    name: mobileuser.secret
  role: admin
  developerAccountRef:
    name: mobile-developeraccount
  providerAccountRef:
    name: 3scale-tenant-secret

---


apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperUser
metadata:
  name: ron.mobile
spec:
  username: ron.mobile
  email: ron@globex.com
  passwordCredentialsRef:
    name: mobileuser.secret
  role: member
  developerAccountRef:
    name: partner-developeraccount
  providerAccountRef:
    name: mobile-developeraccount