apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: cashback-order-connector
spec:
  dependencies:
    - 'camel:http'
  flows:
    - from:
        steps:
          - log:
              logging-level: INFO
              message: 'Order event received: ${body}'
          - setHeader:
              expression:
                constant: POST
              name: Exchange.HTTP_METHOD
          - setHeader:
              expression:
                constant: application/json
              name: Exchange.CONTENT_TYPE
          - to: '{{cashback-service.url}}'
        uri: >-
          kafka:{{kafka.order.topic.name}}?groupId={{kafka.order.consumer.group}}&autoOffsetReset=earliest
  traits:
    camel:
      configuration:
        properties:
          - kafka.order.topic.name = globex.order-aggregated
          - kafka.order.consumer.group = order-cashback-connector-3
          - 'cashback-service.url = http://cashback-service:8080/expense'
          - 'camel.component.kafka.brokers = {{bootstrapServer}}'
          - 'camel.component.kafka.securityprotocol = {{securityProtocol}}'
          - 'camel.component.kafka.saslmechanism = {{saslMechanism}}'
          - 'camel.component.kafka.sasljaasconfig = {{saslJaasConfig}} '
    mount:
      configuration:
        configs:
          - 'secret:kafka-client-secret'
